---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Update installed packages
  apt:
    state: latest
    upgrade: safe

- name: Install/update docker
  apt:
    name: docker.io
    state: latest

- name: Automatically prune docker containers
  cron:
    name: "Prune docker containers"
    minute: "17"
    hour: "3"
    job: "docker system prune -af"
